build_failure_conditions:
    - 'elements.rating(<= D).exists'
    - 'issues.label("coding-style").exists'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 8)'

tools:
    php_sim: false
    php_pdepend: true
    php_analyzer:
        config:
            checkstyle:
                enabled:              true
                no_trailing_whitespace:  true
    php_code_sniffer:
        enabled:              true
        config:
            standard:             PSR2
    sensiolabs_security_checker: true
